### ISSUE TITLE
Better error messages when interactive can't find fstar.exe

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/fstar-interactive#1]
Currently I'm getting `Unable to execute: undefined` when typing `Ctrl+Shift+I` in `tinyfstar-new.fst`
![screenshot from 2015-05-14 22-59-39](https://cloud.githubusercontent.com/assets/5850655/7641822/8952dd6a-fa8c-11e4-819e-98479d8f65c5.png)

**Comment by catalin-hritcu** [comment]
Finally understood what the README meant by "You need a working installation of F\* available in your default path" (`export PATH=bin/:$PATH` <-- note: this was wrong too, need to use absolute path). Next problem is this:

```
Uncaught Error: write EPIPE
events.js:141
Stack Trace:
Error: write EPIPE
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at WriteWrap.afterWrite (net.js:753:14)
```

![screenshot from 2015-05-14 23-09-05](https://cloud.githubusercontent.com/assets/5850655/7642026/0e9d99dc-fa8e-11e4-9de1-b97cc71003a5.png)

**Atom Version**: 0.199.0
**System**: linux 4.0.1-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at WriteWrap.afterWrite (net.js:753:14)
```

### Commands

```
     -0:00.3.0 fstar-interactive:trigger (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "autohide-tree-view",
      "FSharp"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 18
  }
}
```

### Installed Packages

``` coffee
# User
build, v0.31.0
fstar-interactive, v0.1.0
language-fsharp, v0.8.4
language-fstar, v0.0.1

# Dev
No dev packages
```

**Comment by nikswamy** [comment]
Can you try with the OCaml version of F*? That way we can also eliminate mono vs. .net from the equation.

**Comment by catalin-hritcu** [comment]
Was already using the OCaml version. Tried building it again and it didn't change anything.

**Comment by nikswamy** [comment]
We should share screens probably ... I can't reproduce this here.

**Comment by nikswamy** [comment]
Does `fstar --in` work for you independently of Atom?
Try `fstar --in` and then enter the following on the console

```
module Test
let x = 0
#end
```

It should print `ok`

**Comment by catalin-hritcu** [comment]
Yes, `fstar.exe --in` works fine from the command line. I've already fixed the `fstar.exe` in the `fstar-interactive` code (extensions are not optional outside Windows). It didn't change anything.

**Comment by catalin-hritcu** [comment]
Ok, here's a new error. Not sure it's not just a bad state caused by the debugger though:

![screenshot from 2015-05-15 00-49-11](https://cloud.githubusercontent.com/assets/5850655/7643675/d9a389f4-fa9b-11e4-99dd-9cd215db9a35.png)

**Atom Version**: 0.199.0
**System**: linux 4.0.1-1-ARCH
**Thrown From**: [fstar-interactive](https://github.com/FStarLang/fstar-interactive) package, v0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of null

```
At /home/hritcu/Projects/fstar/fstar-interactive/lib/fstar-interactive.js:225

TypeError: Cannot read property 'stdin' of null
  at Object.module.exports.checkSelection (/home/hritcu/Projects/fstar/fstar-interactive/lib/fstar-interactive.js:225:15)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -9:08.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -9:08.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -9:07.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -9:07.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -9:07.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -9:07.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -9:07.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -9:07.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -8:22.1.0 fstar-interactive:trigger (atom-text-editor.editor.is-focused)
     -6:38.5.0 settings-view:open (atom-text-editor.editor)
     -4:26.9.0 fstar-interactive:trigger (atom-text-editor.editor.is-focused)
     -0:21.1.0 core:move-to-top (atom-text-editor.editor.is-focused)
  3x -0:19.6.0 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:18.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:13.5.0 fstar-interactive:stop (atom-text-editor.editor.is-focused)
     -0:04.2.0 fstar-interactive:trigger (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "autohide-tree-view",
      "FSharp"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
build, v0.31.0
fstar-interactive, v0.1.0
language-fsharp, v0.8.4
language-fstar, v0.0.1

# Dev
No dev packages
```

**Comment by catalin-hritcu** [comment]
Some atom issues that seem relevant here:
https://github.com/atom/atom/issues/5507
https://github.com/atom/atom/issues/4708

**Comment by catalin-hritcu** [comment]
The TypeError only occurs in the debugger. For the EPIPE error here is what gets printed in the console log:

```
Activating F* interactive!
index.js:52 Window load time: 985ms
/home/hritcu/Projects/fstar/fstar-interactive/lib/fstar-interactive.js:148 undefined  
/home/hritcu/Projects/fstar/fstar-interactive/lib/fstar-interactive.js:204 currentPos is (4, 0)
/home/hritcu/Projects/fstar/fstar-interactive/lib/fstar-interactive.js:205 lastMarker end is (0, 0)
/home/hritcu/Projects/fstar/fstar-interactive/lib/fstar-interactive.js:211 nextRange is (0, 0),(4, 0)
/home/hritcu/Projects/fstar/fstar-interactive/lib/fstar-interactive.js:222 Sending selection to process:
module TinyFStarNew

open Classical
open FunctionalExtensionality

events.js:141 Uncaught Error: write EPIPE
```

**Comment by catalin-hritcu** [comment]
After a bit of debugging I noticed that the call to `child_process.spawn` returned null, so I stepped into this and got this printed in the console:

```
Uncaught Error: spawn fstar.exe ENOENT
```

as well as a popup about this:
![screenshot from 2015-05-15 01-12-18](https://cloud.githubusercontent.com/assets/5850655/7644030/64e3d002-fa9f-11e4-97ec-1d20b5bc190e.png)

I was adding a relative path instead of an absolute one to the `$PATH`, and that was causing the problem. With the proper `$PATH` all this works well:

![screenshot from 2015-05-15 01-20-37](https://cloud.githubusercontent.com/assets/5850655/7644084/38709f18-faa0-11e4-9187-3750dbc5a408.png)

Some proper error handing in the interactive seems needed, otherwise the errors atom displays are completely useless in this case.

**Comment by beurdouche** [comment]
I am trying to make the interactive mode to work on my Mac.
I do have `/opt/fstar/bin` in my `PATH` variable. I also added a symlink in bin from `fstar.exe` to `fstar` (just in case).
The module loads well and when I toogle Ctrl+Shift+I I see the blue zone down to the cursor but I get an error.

Any advices ?
Thanks !
![screen shot 2015-05-23 at 20 47 15](https://cloud.githubusercontent.com/assets/1193431/7785452/e77cffaa-0190-11e5-8d9c-d4d500989c29.png)

**Comment by catalin-hritcu** [comment]
What error?

**Comment by beurdouche** [comment]
Unable to execute : undefined (Uploaded screenshot above)

**Comment by catalin-hritcu** [comment]
Error messages like this are rather useless. Try to get more information in `View > Developer > Toggle Developer Tools`. See for instance if anything gets printed in the console beyond this error.

**Comment by beurdouche** [comment]
Ok, it is an `Uncaught Error: write EPIPE` in `event.js 141`
I have the absolute path to my fstar bin directory in my PATH.

I am trying to debug but it is not very clear =s

![screen shot 2015-05-23 at 21 13 31](https://cloud.githubusercontent.com/assets/1193431/7785447/9dbf530e-0190-11e5-81be-383ae662c3e3.png)

**Comment by catalin-hritcu** [comment]
Just double checking: have you restarted atom since changing your PATH? You need to do that.

**Comment by beurdouche** [comment]
Yes I did ..

**Comment by beurdouche** [comment]
Ok, I did find the problem.
It seems that PATH wasn’t taken into account by Atom.
I started Atom from the terminal and it worked…
I did restart my system before starting Atom from my Dock though.

Thanks !

**Comment by catalin-hritcu** [comment]
Any chance for giving out a better error message in such cases?
