### ISSUE TITLE
Uncaught TypeError: Cannot read property 'shift' of undefined

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/fstar-interactive#2]
Seems like a problem with parsing errors?

![screenshot from 2015-05-15 01-38-17](https://cloud.githubusercontent.com/assets/5850655/7644329/b91a7e2e-faa3-11e4-9721-a59ec8cadd86.png)
1. Load file with error and try to check it (Ctrl + Shift + I)
2. Packages > F\* Interactive > Next error (Alt + Ctrl + G)
3. Uncaught TypeError: Cannot read property 'shift' of undefined

**Atom Version**: 0.199.0
**System**: linux 4.0.1-1-ARCH
**Thrown From**: [fstar-interactive](https://github.com/FStarLang/fstar-interactive) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'shift' of undefined

```
At /home/hritcu/Projects/fstar/fstar-interactive/lib/fstar-interactive.js:291

TypeError: Cannot read property 'shift' of undefined
    at Object.module.exports.nextError (/home/hritcu/Projects/fstar/fstar-interactive/lib/fstar-interactive.js:291:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:153:19)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:71:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
```
### Commands

```
     -0:32.3.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:29.3.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:28.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:27.6.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -0:27.4.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:26.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:25.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:25.3.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:23.1.0 fstar-interactive:trigger (atom-text-editor.editor.is-focused)
     -0:00.3.0 fstar-interactive:next-error (div.build.tool-panel.panel-bottom.native-key-bindings)
```

**Comment by nikswamy** [comment]
Is this still a problem? I haven't been able to reproduce it.

**Comment by catalin-hritcu** [comment]
This works well now indeed.
